version: "3"

services:
  dispatcher:
    image: nginx
    container_name: dispatcher-nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    stdin_open: true
    tty: true
